{% set name = "pyslice" %}
{% set version = "6.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyslice-{{ version }}.tar.gz
  sha256: 42765460d5a98f7a17ae3f569caf9a79a2829fd3a0528ad12fe28b0c1a3c4a24

build:
  entry_points:
    - pyslice = pyslice:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - binaryornot
    - numpy

test:
  imports:
    - pyslice
  commands:
    - pip check
    - pyslice --help
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: Specialized templating engine do develop a parameterized set of model data sets
  home: https://pypi.org/project/pyslice/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
